version: '3.8'

services:
  apache-ignite:
    image: apacheignite/ignite:latest
    container_name: apache-ignite
    ports:
      - "10800:10800"  # Port for Ignite native communication
      - "47100:47100"  # Port for Ignite discovery
      - "47500:47500"  # Port for Ignite discovery
      - "49112:49112"  # Port for Ignite JMX monitoring
    environment:
      - IGNITE_QUIET=false  # Enables logging output
      - IGNITE_USER=username  # Replace with your Ignite username
      - IGNITE_PASSWORD=password  # Replace with your Ignite password
      - IGNITE_CONFIG_URL=https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-ignite.xml
    networks:
      - spark-net

  # spark-master:
  #   image: bitnami/spark:latest
  #   container_name: spark-master
  #   environment:
  #     - SPARK_MODE=master
  #     - SPARK_MASTER_PORT=7077
  #     - SPARK_MASTER_WEBUI_PORT=8080
  #   ports:
  #     - "7077:7077"  # Spark Master Port
  #     - "8080:8080"  # Spark Master Web UI Port
  #   networks:
  #     - spark-net

  # spark-worker:
  #   image: bitnami/spark:latest
  #   container_name: spark-worker
  #   environment:
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://spark-master:7077
  #   depends_on:
  #     - spark-master

  spark-notebook:
    image: jupyter/pyspark-notebook
    container_name: pyspark-notebook
    ports:
      - "8888:8888"  # Port for Jupyter Notebook
      - "4040:4040"
      - "10000:10000"  # Port for Spark Thrift Server
    environment:
      - PYSPARK_ALLOW_INSECURE_GATEWAY=1  # Allows insecure connection to Spark
      # - SPARK_OPTS="--master spark://spark-master:7077"  # Connect notebook to Spark cluster

    networks:
      - spark-net
networks:
  spark-net:
    driver: bridge
