version: '3.8'

services:
  apache-ignite:
    image: apacheignite/ignite:latest
    container_name: apache-ignite
    ports:
      - "10800:10800"
      - "47100:47100"
      - "47500:47500"
      - "49112:49112"
    environment:
      - IGNITE_QUIET=false  # Enables logging output
      - IGNITE_CONFIG_URL=https://raw.githubusercontent.com/apache/ignite/master/examples/config/example-ignite.xml
    networks:
      - spark-net
    volumes:
      - ../../../service-docker-compose/volumes/apache-ignite:/data # Mount volume

  spark-notebook:
    image: jupyter/pyspark-notebook
    container_name: pyspark-notebook
    ports:
      - "8800:8888"
      - "4040:4040"
      - "8080:8080"
      - "10000:10000"
    environment:
      - GRANT_SUDO=yes
      - PYSPARK_ALLOW_INSECURE_GATEWAY=1
      - JUPYTER_TOKEN=your_static_token
    volumes:
      - ../../../service-docker-compose/volumes/jupyter:/home/jovyan/work  # Mount volume

    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge
